apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vfw8dbkkf-go 
  janus-idp.io/tekton: vfw8dbkkf-go
  backstage.io/kubernetes-id: vfw8dbkkf-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vfw8dbkkf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml